app:
    image: busybox:latest
    #build: ./docker/app/
    volumes:
        - /srv/docker/symfony-demo:/srv
    #command: tail -f /dev/null # or
    tty: true

mysql:
    image: mysql:latest
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
        - '3306:3306'

fpm:
    #image: php:fpm
    build: ./docker/fpm/
    volumes_from:
        - app
    links:
        - mysql
    ports:
        - '9000:9000'

nginx:
    #image: nginx:latest
    build: ./docker/nginx/
    volumes_from:
        - app
    links:
        - fpm
    ports:
        - '80:80'
        - '443:443'
